- name: check load avg and send email
  hosts: all
  tasks:
   - name: Get the load avg
     shell: uptime
     register: out
     
   - name: fetch the load avg
     set_fact:
      #LOAD: "{{out.stdout.split()[-3].split('.')[0]}}"
       LOAD: "6"
   - name: send email
     shell: curl abc.com
     when: LOAD > "5"
   

