- name: check load avg and send email
  hosts: all
  tasks:
   - name: Get the load avg
     shell: uptime
     register: out
     
   - name: fetch the load avg
     debug:
      msg: "{{out.stdout.split()[-3].split('.')[0]}}"

