- name: Install webserver
  hosts: all
  tasks:
    - name: install webserver
      package:
        name: httpd
        state: present
     
    - name: Start httpd
      services:
        name: httpd
        state: started
