- name: Install webserver
  hosts: all
  tasks:
   - name: install webserver
     package:
     - name: webserver
       state: Present
     
- name: Start httpd
   services:
   - name: httpd
     state: started
