- name: Register a variable from output of one task
  hosts: all
  tasks:
   - name: Get Uptime
     shell: uptime
     register: OUT
     
   - name: Print OUT variable
     debug:
      msg: "{{OUT}}"
